Month7 (steps 1 and 2)
DashaSites/react-stellar-burger pull request #1
Opened 2023-07-08 19:02 UTC by DashaSites

2023-07-08 19:44 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Есть отписка от слушателя событий
- Проект соответствует макету
- Хорошая работа с `propTypes`

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Добавьте проверку успешности запроса
- закрытие модального окна по ESC должно быть описано в компоненте Modal
- Булки в конструкторе не должны скроллиться, должен скролиться только контент между ними.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-07-08 19:44 UTC, andryxxa93 commented on src/components/app/app.jsx
> +    fetch(`${url}`, {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-07-08 19:44 UTC, andryxxa93 commented on src/components/app/app.jsx
> +    .then(res => res.json())
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-07-08 19:44 UTC, andryxxa93 commented on src/components/app/app.jsx
> +  const handleEscKeydown = (event) => {
**Надо исправить**

закрытие попапа по ESC относится к функционалу модального окна и должно быть описано в компоненте Modal, вешайте обработчик при открытии (монтировании) и удаляйте закрытии (размонтировании) применив useEffect

2023-07-08 19:44 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +  ingredients: PropTypes.arrayOf(PropTypes.shape({
**Надо исправить**

во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать

2023-07-08 19:44 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +Modal.propTypes = {
**Необходимо исправить**
В propTypes `Modal ` не хватает пропа `children`

2023-07-08 19:44 UTC, andryxxa93 commented on src/components/ingredient/ingredient.jsx
> +    _id: PropTypes.string,
**Можно лучше**
У полей объекта так же необходимо ставить `isRequired`

2023-07-08 19:44 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  ingredients: PropTypes.arrayOf(PropTypes.shape({
**Можно лучше**
послей закрывающей скобки `shape ` так же необходимо ставить `isRequired`

2023-07-08 19:44 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  const buns = ingredients.filter((element) => { // вытаскиваем из всех данных массив булок
**Можно лучше**
Сложные операции желательно оборачивать в хук `useMemo` чтобы избежать ненужных выполнений. 
https://ru.reactjs.org/docs/hooks-reference.html#usememo

2023-07-09 19:39 UTC, DashaSites commented on src/components/ingredient/ingredient.jsx
> +    _id: PropTypes.string,
+

2023-07-09 19:39 UTC, DashaSites commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  ingredients: PropTypes.arrayOf(PropTypes.shape({
++

2023-07-09 19:57 UTC, DashaSites commented on src/components/modal/modal.jsx
> +Modal.propTypes = {
++

2023-07-09 21:46 UTC, DashaSites commented on src/components/burger-constructor/burger-constructor.jsx
> +  ingredients: PropTypes.arrayOf(PropTypes.shape({
++

2023-07-10 19:47 UTC, DashaSites commented on src/components/app/app.jsx
> +  const handleEscKeydown = (event) => {
++

2023-07-10 21:45 UTC, DashaSites commented on src/components/app/app.jsx
> +    .then(res => res.json())
++

2023-07-10 22:39 UTC, DashaSites commented on src/components/app/app.jsx
> +    fetch(`${url}`, {
++

2023-07-11 11:31 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-07-11 14:55 UTC, merged