Month 8/step 1
DashaSites/react-stellar-burger pull request #2
Opened 2023-07-29 18:19 UTC by DashaSites

Pull request, take one

2023-07-29 18:32 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Правильно используете контекст
- Использовали useReducer
- Нет лишнего кода

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

**Необходимо исправить**
- В консоли есть ошибки связанные с propTypes
<img width="581" alt="Снимок экрана 2023-07-29 в 21 31 04" src="https://github.com/DashaSites/react-stellar-burger/assets/60173362/d972932e-3992-448f-8b1a-4f9b4868bb2d">

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-07-29 18:32 UTC, andryxxa93 commented on src/components/app/app.jsx
> +    .catch(err => console.log(err));
**Можно лучше**
хорошо, что обрабатывается ошибка запроса к api, но можно сделать еще лучше - сохранять в state и показывать пользователю ошибку в интерфейсе, чтобы он понимал что происходит

2023-07-29 18:32 UTC, andryxxa93 commented on src/components/app/app.jsx
> +        <IngredientsContext.Provider value={{ingredients, setIngredients}}> {/* сохраняю стейт в контекст */}
**Можно лучше**

такая запись значения контекста приводит к тому, что при каждом рендере App даже не связанным с изменением значения контекста будет создаватсья новый объект и передаваться новое значение контекста, это приведет к перерендеру всех компонентов использующих контекст

Нужно обернуть создание объекта в useMemo, как показано в этой статье https://hswolff.com/blog/how-to-usecontext-with-usereducer/ в разделе Performance Concerns

2023-07-31 10:32 UTC, DashaSites commented on src/components/app/app.jsx
> +    .catch(err => console.log(err));
++

2023-07-31 10:53 UTC, DashaSites commented on src/components/app/app.jsx
> +        <IngredientsContext.Provider value={{ingredients, setIngredients}}> {/* сохраняю стейт в контекст */}
++

2023-07-31 19:36 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-07-31 20:20 UTC, merged